# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3cd12f9d2fef30d43253d311d2d76cfb9e6854003232925c67b80958241114fd90637d22163777243cba34a952610aa55c9fe4d9e8677d79af77416dfe77729

test:
  secret_key_base: 31e9cc85bcf7ba3b3dd24a1e57254b2b51b66084e2f779d49548f6c81dca18566cb2810d88f9dab68d18aff5cfba8a9bc8acbfe8ab4b452aab2e731526f9f6bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
